name: Happy New Year Automation 🎉

on:
  schedule:
    - cron: '0 0 1 1 *'   # 1er janvier à 00h00 UTC
  workflow_dispatch:

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Debug - show repo tree
        run: |
          echo "Current directory:"
          pwd
          echo "Repository content:"
          ls -R

      - name: Run New Year Script
        run: python script/new_year.py
